// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: proto/task.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "task";

export interface User {
  id: number;
  username: string;
  role: string;
}

export interface Task {
  id: number;
  title: string;
  requiredSkills: string[];
  priority: string;
  status: string;
  users: User | null;
}

export interface CreateTaskRequest {
  title: string;
  requiredSkills: string[];
  priority: string;
  status: string;
  assignedTo: number;
}

export interface CreateTaskResponse {
  task: Task | undefined;
}

export interface GetTaskRequest {
  id: number;
}

export interface GetTaskResponse {
  task: Task | undefined;
}

export interface UpdateTaskRequest {
  id: number;
  title: string;
  requiredSkills: string[];
  priority: string;
  status: string;
  assignedTo: number;
}

export interface UpdateTaskResponse {
  task: Task | undefined;
}

export interface DeleteTaskRequest {
  id: number;
}

export interface DeleteTaskResponse {
  success: boolean;
}

/** Optional: Add filters or pagination if needed */
export interface ListTasksRequest {
}

export interface ListTasksResponse {
  tasks: Task[];
}

export interface AddUserToTaskRequest {
  taskId: number;
}

export interface AddUserToTaskResponse {
  task: Task | undefined;
  empty: Empty | undefined;
}

export interface Empty {
}

export const TASK_PACKAGE_NAME = "task";

export interface TaskServiceClient {
  createTask(request: CreateTaskRequest): Observable<CreateTaskResponse>;

  getTask(request: GetTaskRequest): Observable<Task>;

  updateTask(request: UpdateTaskRequest): Observable<Task>;

  deleteTask(request: DeleteTaskRequest): Observable<DeleteTaskResponse>;

  listTasks(request: ListTasksRequest): Observable<ListTasksResponse>;

  assignTasks(request: Empty): Observable<ListTasksResponse>;

  manuallyReassignTask(request: AddUserToTaskRequest): Observable<ListTasksResponse>;
}

export interface TaskServiceController {
  createTask(
    request: CreateTaskRequest,
  ): Promise<CreateTaskResponse> | Observable<CreateTaskResponse> | CreateTaskResponse;

  getTask(request: GetTaskRequest): Promise<Task> | Observable<Task> | Task;

  updateTask(request: UpdateTaskRequest): Promise<Task> | Observable<Task> | Task;

  deleteTask(
    request: DeleteTaskRequest,
  ): Promise<DeleteTaskResponse> | Observable<DeleteTaskResponse> | DeleteTaskResponse;

  listTasks(request: ListTasksRequest): Promise<ListTasksResponse> | Observable<ListTasksResponse> | ListTasksResponse;

  assignTasks(request: Empty): Promise<ListTasksResponse> | Observable<ListTasksResponse> | ListTasksResponse;

  manuallyReassignTask(
    request: AddUserToTaskRequest,
  ): Promise<ListTasksResponse> | Observable<ListTasksResponse> | ListTasksResponse;
}

export function TaskServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createTask",
      "getTask",
      "updateTask",
      "deleteTask",
      "listTasks",
      "assignTasks",
      "manuallyReassignTask",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TaskService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TaskService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TASK_SERVICE_NAME = "TaskService";
